# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qtlayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1112, 700)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        self.annimGBox = QtWidgets.QGroupBox(Form)
        self.annimGBox.setGeometry(QtCore.QRect(11, 11, 1090, 624))
        self.annimGBox.setObjectName("annimGBox")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 640, 1091, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.simTypeCBox = QtWidgets.QComboBox(self.widget)
        self.simTypeCBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.simTypeCBox.setFrame(True)
        self.simTypeCBox.setObjectName("simTypeCBox")
        self.simTypeCBox.addItem("")
        self.simTypeCBox.addItem("")
        self.simTypeCBox.addItem("")
        self.horizontalLayout_4.addWidget(self.simTypeCBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LEditLabel1 = QtWidgets.QLabel(self.widget)
        self.LEditLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LEditLabel1.setObjectName("LEditLabel1")
        self.horizontalLayout.addWidget(self.LEditLabel1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit1.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit1.setObjectName("lineEdit1")
        self.horizontalLayout.addWidget(self.lineEdit1)
        self.LEditUnit1 = QtWidgets.QLabel(self.widget)
        self.LEditUnit1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LEditUnit1.setObjectName("LEditUnit1")
        self.horizontalLayout.addWidget(self.LEditUnit1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LEditLabel1_2 = QtWidgets.QLabel(self.widget)
        self.LEditLabel1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LEditLabel1_2.setObjectName("LEditLabel1_2")
        self.horizontalLayout_2.addWidget(self.LEditLabel1_2)
        self.lineEdit2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit2.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout_2.addWidget(self.lineEdit2)
        self.LEditUnit2 = QtWidgets.QLabel(self.widget)
        self.LEditUnit2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LEditUnit2.setObjectName("LEditUnit2")
        self.horizontalLayout_2.addWidget(self.LEditUnit2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LEditLabel1_3 = QtWidgets.QLabel(self.widget)
        self.LEditLabel1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LEditLabel1_3.setObjectName("LEditLabel1_3")
        self.horizontalLayout_3.addWidget(self.LEditLabel1_3)
        self.lineEdit3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit3.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit3.setObjectName("lineEdit3")
        self.horizontalLayout_3.addWidget(self.lineEdit3)
        self.LEditUnit3 = QtWidgets.QLabel(self.widget)
        self.LEditUnit3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LEditUnit3.setObjectName("LEditUnit3")
        self.horizontalLayout_3.addWidget(self.LEditUnit3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.annotCkBox = QtWidgets.QCheckBox(self.widget)
        self.annotCkBox.setObjectName("annotCkBox")
        self.horizontalLayout_4.addWidget(self.annotCkBox)
        self.goButton = QtWidgets.QPushButton(self.widget)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout_4.addWidget(self.goButton)
        self.simTypeCBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.annimGBox.setTitle(_translate("Form", "Animation"))
        self.simTypeCBox.setItemText(0, _translate("Form", "Spring Rate"))
        self.simTypeCBox.setItemText(1, _translate("Form", "Spring Preload"))
        self.simTypeCBox.setItemText(2, _translate("Form", "Airgap"))
        self.LEditLabel1.setText(_translate("Form", "Beginning"))
        self.LEditUnit1.setText(_translate("Form", "UNITS"))
        self.LEditLabel1_2.setText(_translate("Form", "End"))
        self.LEditUnit2.setText(_translate("Form", "UNITS"))
        self.LEditLabel1_3.setText(_translate("Form", "Animation Length"))
        self.LEditUnit3.setText(_translate("Form", "UNITS"))
        self.annotCkBox.setText(_translate("Form", "Annotations"))
        self.goButton.setText(_translate("Form", "Render"))

